# docker/nginx/Dockerfile
# Utilisation de l'image officielle Nginx version 1.20 comme base
FROM nginx:1.20

# Ajout du fichier de configuration NGINX dans le répertoire conf.d
ADD helloworld.nginx.conf /etc/nginx/conf.d/default.conf
